#!/bin/bash
if [[ -z "$1" ]]; then
    echo "z"
    exit
fi
letters=${1,,}
sum=0

for ((i=0; i<${#letters}; i++))
do
    letter="${letters:i:1}"
    value=$(( $(printf "%d" "'$letter") - 96 ))
    sum=$((sum + value))
done

sum=$(( (sum - 1) % 26 + 1 ))

printf "\\$(printf '%03o' $((sum + 96)))\n"
