#!/bin/bash
if (( $1 > $2 )); then
    start=$2
    end=$1
else
    start=$1
    end=$2
fi

sum=0
if (( $1 == $2 )); then
    echo $1
else
    for ((i=$start; i<=$end; i++))
    do
      sum=$(( sum + i ))
    done
    echo $sum
fi
