#!/bin/bash

s="$1"
x=0
o=0

for ((i=0; i<${#s}; i++))
do
    char="${s:i:1}"
    if [[ $char == "x" ]] || [[ $char == "X" ]]; then
        x=$((x+1))
    elif [[ $char == "o" ]] || [[ $char == "O" ]]; then
        o=$((o+1))
    fi
done

if ((x==o));
then
    echo "true"
else
    echo "false"
fi
